### ISSUE TITLE
Use dylib extension for darwin

### ISSUE THREAD

**Issue by jvlmdr** [chfin/cl-portmidi#1]
I installed portmidi on OS X from the [homebrew formula](https://formulae.brew.sh/formula/portmidi) and it created `libportmidi.dylib` rather than `.so`. This led to an error when I did `(ql:quickload :portmidi)` since it could not find the `.so` file. I was able to fix this by adding the line `(:darwin "libportmidi.dylib")` before `(:unix ...)` in `setup.lisp`.

**Comment by chfin** [comment]
Thanks for the report! I added your suggestion, but I can't test it here. Could you confirm that it works for you?

That being said, I'm a bit surprised that this still works at all. I don't really use CL anymore, so I don't maintain this library. In case you intend to do a bit more with it, feel free to create a fork. Maybe then you also want to put it on Quicklisp.

**Comment by jvlmdr** [comment]
Hey, yep, I can confirm that it works on my mac laptop (OS X 11.2) with portmidi version `217_2` installed with homebrew
