### ISSUE TITLE
open-input returns nil instead of stream pointer

### ISSUE THREAD

**Issue by jvlmdr** [chfin/cl-portmidi#2]
The conditional form in `open-input` seems incorrect:
https://github.com/chfin/cl-portmidi/blob/828f94da290b55b5786ab497e90e63506aed627f/portmidi.lisp#L74-L76

When there is no error, it simply returns nil because there was no matching clause.

It should probably be the same as `open-output`:
https://github.com/chfin/cl-portmidi/blob/828f94da290b55b5786ab497e90e63506aed627f/portmidi.lisp#L89-L91

**Comment by chfin** [comment]
Sorry for the late reply (I completely missed this) and thanks for the bug report. Should be fixed now.
